name: Demo - Workflow activity type
on: 
  pull_request:
    branches:
      - stage
    types:
      - opened
      - edited
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test