name: branch main
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build-site
          path: dist/
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-site
          path: download-data/
      
      - name: Display structure of downloaded files
        run: ls -R download-data
      
      - name: Deploy to server
        run: echo "Deploying to server"